name: UltimateGrenades
main: com.lavacraftserver.UltimateGrenades.UltimateGrenades
version: 1.2
authors: [np98765, MrBluebear3]
commands:
  grenade:
    usage: /<command> [grenade-type]
    description: Boom.
